### ISSUE TITLE
mask_from_label.cpp does not output correct pixel label

### ISSUE THREAD

**Issue by alphadadajuju** [scenenn/shrec17#1]
Hello,
I tried to use the "mask_from_label.cpp" to decode a rgb 2d-label image. I expected to see the decoded value of a pixel from an object to match the label ID of that object in the provided xml file. However this was never the case.

Is this actually the right way to convert from rgb channels to label ID? 
Thank you very much in advance! Amazing indoor dataset!

Best,

**Comment by songuke** [comment]
Thanks for the report. It seems somebody else also reported the same issue.
Let me check what happens.

2018-05-19 5:06 GMT+09:00 alphadadajuju <notifications@github.com>:

**Comment by mktdev** [comment]
@alphadadajuju 
I am able to extract the binary images correctly. Note that the object might only have few pixels in the frames thus the binary image output might look like it is blank (black).

This is an example command when the output is not blank (object id: 005_610041)

`
 ./mask_from_label 005/mask/mask_image01000.png 610041 output.png 
`
